export const notifications = [
  {
    id: 1,
    user_id: 1,
    type: "like",
    reference_id: 1,
    message: "@user2 gönderini beğendi",
    is_read: true,
    created_at: "2024-01-21T10:30:00Z",
  },
  {
    id: 2,
    user_id: 1,
    type: "comment",
    reference_id: 1,
    message: "@user3 gönderine yorum yaptı",
    is_read: false,
    created_at: "2024-01-21T11:45:00Z",
  },
  {
    id: 3,
    user_id: 2,
    type: "follow",
    reference_id: 1,
    message: "@user4 seni takip etmeye başladı",
    is_read: false,
    created_at: "2024-01-21T12:15:00Z",
  },
  {
    id: 4,
    user_id: 1,
    type: "chat",
    reference_id: 1,
    message: "@user2'den yeni mesajın var",
    is_read: false,
    created_at: "2024-01-21T14:30:00Z",
  },
  {
    id: 5,
    user_id: 3,
    type: "like",
    reference_id: 2,
    message: "@user1 gönderini beğendi",
    is_read: true,
    created_at: "2024-01-21T15:20:00Z",
  },
];
