export const topics = [
  {
    id: 1,
    name: "Teknoloji",
    description: "Teknoloji dünyasındaki en son gelişmeler",
    icon: "💻",
    color: "#007AFF",
  },
  {
    id: 2,
    name: "Oyun",
    description: "Video oyunları ve gaming kültürü",
    icon: "🎮",
    color: "#5856D6",
  },
  {
    id: 3,
    name: "Bilim",
    description: "Bilimsel keşifler ve araştırmalar",
    icon: "🔬",
    color: "#FF2D55",
  },
  {
    id: 4,
    name: "Sanat",
    description: "Sanat, tasarım ve yaratıcılık",
    icon: "🎨",
    color: "#FF9500",
  },
  {
    id: 5,
    name: "Müzik",
    description: "Müzik dünyasından haberler ve tartışmalar",
    icon: "🎵",
    color: "#5856D6",
  },
  {
    id: 6,
    name: "Spor",
    description: "Spor haberleri ve analizler",
    icon: "⚽",
    color: "#34C759",
  },
  {
    id: 7,
    name: "Film & TV",
    description: "Film ve dizi dünyasından güncellemeler",
    icon: "🎬",
    color: "#FF3B30",
  },
  {
    id: 8,
    name: "Yemek",
    description: "Yemek tarifleri ve gastronomi",
    icon: "🍳",
    color: "#FF9500",
  },
  {
    id: 9,
    name: "Seyahat",
    description: "Gezi rehberleri ve seyahat önerileri",
    icon: "✈️",
    color: "#007AFF",
  },
  {
    id: 10,
    name: "Kitap",
    description: "Kitap önerileri ve edebiyat tartışmaları",
    icon: "📚",
    color: "#5856D6",
  },
  {
    id: 11,
    name: "Sağlık",
    description: "Sağlık ve wellness konuları",
    icon: "🏥",
    color: "#34C759",
  },
  {
    id: 12,
    name: "İş Dünyası",
    description: "Kariyer ve iş dünyası haberleri",
    icon: "💼",
    color: "#FF9500",
  },
  {
    id: 13,
    name: "Eğitim",
    description: "Eğitim ve öğrenme kaynakları",
    icon: "📚",
    color: "#007AFF",
  },
  {
    id: 14,
    name: "Moda",
    description: "Moda trendleri ve stil önerileri",
    icon: "👗",
    color: "#FF2D55",
  },
  {
    id: 15,
    name: "Otomotiv",
    description: "Otomobil dünyasından haberler",
    icon: "🚗",
    color: "#FF3B30",
  },
];
